# Generated by Django 3.2.18 on 2023-02-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230217_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='fname',
            new_name='name',
        ),
    ]
