# Generated by Django 3.2.18 on 2023-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
